logo: 程序•袁
title: CLEAN CODER
description: 袁慎建的博客
author: 袁慎建


url: http://cleancoder.club
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
#highlighter: rouge
paginate: 10

sass:
  style: compressed


navigation:
 - title: ABOUT
   url: /about

social:
   github: sjyuan-cc
   work_email: sjyuan@thoughtworks.com
   personal_email: sjyuan.cc@gmail.com

gems:
 - jekyll-paginate
 - jekyll-sass-converter
