logo: 程序•袁
title: CLEAN CODER
description: 袁慎建的博客

url: http://cleancoder.club
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
#highlighter: rouge
paginate: 10

sass:
  style: compressed


navigation:
 - title: ABOUT
   url: /about

social:
   github: yuanshenjian
   email: sjyuan@thoughtworks.com

gems:
 - jekyll-paginate
 - jekyll-sass-converter

google_analytics: "UA-58263416-1"
