logo: 程序•袁
title: CLEAN CODER
description: 袁慎建的博客
author: 袁慎建


url: http://blog.sjyuan.cc
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
#highlighter: rouge
#lsi: false
#excerpt_separator: "\n\n"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

paginate: 10

toc_levels: 1 ..4

sass:
  style: compressed


navigation:
 - title: ABOUT
   url: /about

social:
   github: sjyuan-cc
   work_email: sjyuan@thoughtworks.com
   personal_email: sjyuan.cc@gmail.com

gems:
 - jekyll-paginate
 - jekyll-sass-converter
